import type { NextPage } from 'next'
import Head from 'next/head'
import { Form } from '../components/Form'
import styles from '../styles/Home.module.css'
import { AppBar } from '../components/AppBar'
import { AccountList } from '../components/AccountList'

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Solana - Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/solana.png" />
      </Head>

      <main className={styles.main}>

        <AppBar />

        <p className={styles.description}>
          A completely on-chain decentralised social media platform built on <b>Solana </b>
        </p>

        <AccountList />

        <p className={styles.subdescription}>
          Create an Account
        </p>

        <Form />

      </main>

      <footer className={styles.footer}>
        Build on top of
        <a
          href="https://examples.anchor-lang.com/"
        >
          Anchor-By-Example
        </a>
      </footer>
    </div>
  )
}

export default Home
